[lint]
ignore = [
    "BLE001",
    "EXE001",
    "PLW1510",
    "DTZ005",
    "S110",
    "RUF059",
    "UP022",
    "PIE810",
    "S112",
    "PLR1722",
    "TRY004",
    "F841",
    "PLW0602",
    "SIM102",
    "PLW1508",
    "DTZ007",
    "RUF013",
    "ISC004",
    "SIM115",
    "TRY002",
    "F811",
    "TRY201",
    "ASYNC210",
    "PTH123",
    "DTZ011",
    "FURB122",
    "B023",
    "G201",
    "RUF012",
    "SIM103",
    "PTH103",
    "PTH118",
    "EXE002",
    "F401",
    "RUF100"
]
