#!/usr/bin/env bash
# Vigilum Codex 2.1 — Guardrail 09 : Zero-Middleman
# Blocks writes to authority domains and intercepts extensions (*.flag, *.token, receipt*.json)
set -eu

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$SCRIPT_DIR/../lib/tesla-exit-codes.sh"
. "$SCRIPT_DIR/../lib/tesla-logging.sh"

staged=$(git diff --cached --name-only --diff-filter=ACM || true)
[ -n "$staged" ] || exit "$TESLA_EXIT_OK"

for f in $staged; do
    case "$f" in
        MVP-GITHUB/* | CERTIFICATES/*)
            agent_env="${TESLA_AGENT_IDENTITY:-orchestrator}"
            if [ "$agent_env" != "tesla-github-manager" ] && [ "${TESLA_ALLOW_AUTHORITY_WRITE:-0}" != "1" ]; then
                tesla_log ERROR "Zero-Middleman violation: Direct write to authority domain blocked for '$f' by '$agent_env'"
                exit "$TESLA_EXIT_ORCH"
            fi
            ;;
        evidence/* | runtime/nonces/* | runtime/gate2/* | runtime/contracts/*)
            agent_env="${TESLA_AGENT_IDENTITY:-orchestrator}"
            if [ "$agent_env" != "system" ] && [ "${TESLA_ALLOW_AUTHORITY_WRITE:-0}" != "1" ]; then
                tesla_log ERROR "Zero-Middleman violation: Direct write to authority domain blocked for '$f' by '$agent_env'"
                exit "$TESLA_EXIT_ORCH"
            fi
            ;;
        *)
            base=$(basename "$f")
            case "$base" in
                *.flag | *.token | receipt*.json)
                    tesla_log ERROR "Zero-Middleman violation: Forbidden artifact pattern (Anti-Théâtre) created outside authority domain: $f"
                    exit "$TESLA_EXIT_ORCH"
                    ;;
                mission_truth.json)
                    tesla_log ERROR "Zero-Middleman violation: mission_truth.json must only reside in runtime/contracts/ and be generated by gate_r.py"
                    exit "$TESLA_EXIT_ORCH"
                    ;;
            esac
            ;;
    esac
done

tesla_log INFO "Hook 09 Zero-Middleman passed"
exit "$TESLA_EXIT_OK"
