name: Gitleaks Secret Scan

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  scan:
    name: Scan for Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0

      - name: Gitleaks
        uses: gitleaks/gitleaks-action@44c470ffc35caa8b1eb3e8012ca53c2f9bea4eb5 # v2

  ci-success:
    needs: [scan]
    runs-on: ubuntu-latest
    steps:
      - run: echo "All checks passed"
